name: Build and Release Core

on:
  repository_dispatch:
    types: [update-modules]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write 

    steps:
      - name: Baixa o código do Core e os Módulos
        uses: actions/checkout@v4
        with:
          submodules: true
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Puxa as últimas atualizações dos módulos
        run: |
          git submodule update --remote --merge
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git commit -am "chore: atualizando módulos via automação [skip ci]" || echo "Nenhuma mudança nos módulos"
          git push || echo "Nada para fazer push"

      - name: Extrai a Versão do Plugin do PHP
        id: extract_version
        run: |
          # Lê o arquivo PHP, acha a linha da versão, recorta só o número e salva na memória do robô
          VERSION=$(grep -i "Version:" vettryx-wp-core.php | head -n 1 | awk -F':' '{print $2}' | xargs)
          echo "PLUGIN_VERSION=$VERSION" >> $GITHUB_ENV

      - name: Empacota o Plugin VETTRYX WP Core
        run: |
          mkdir build
          rsync -av --exclude='.git*' --exclude='.github' ./ build/vettryx-wp-core
          cd build
          zip -r vettryx-wp-core.zip vettryx-wp-core

      - name: Publica a Release Oficial
        uses: softprops/action-gh-release@v2
        with:
          files: vettryx-wp-core.zip
          tag_name: "v${{ env.PLUGIN_VERSION }}"
          name: "VETTRYX WP Core - v${{ env.PLUGIN_VERSION }}"
